package cn.zhengxuan.pojo;

public class Xsxx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Xsxx.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Xsxx.xinming
     *
     * @mbg.generated
     */
    private String xinming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Xsxx.xuehaoid
     *
     * @mbg.generated
     */
    private Integer xuehaoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Xsxx.id
     *
     * @return the value of Xsxx.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Xsxx.id
     *
     * @param id the value for Xsxx.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Xsxx.xinming
     *
     * @return the value of Xsxx.xinming
     *
     * @mbg.generated
     */
    public String getXinming() {
        return xinming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Xsxx.xinming
     *
     * @param xinming the value for Xsxx.xinming
     *
     * @mbg.generated
     */
    public void setXinming(String xinming) {
        this.xinming = xinming == null ? null : xinming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Xsxx.xuehaoid
     *
     * @return the value of Xsxx.xuehaoid
     *
     * @mbg.generated
     */
    public Integer getXuehaoid() {
        return xuehaoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Xsxx.xuehaoid
     *
     * @param xuehaoid the value for Xsxx.xuehaoid
     *
     * @mbg.generated
     */
    public void setXuehaoid(Integer xuehaoid) {
        this.xuehaoid = xuehaoid;
    }
}